site_name: Finallot upload api

docs_dir: src

theme:
  name: material
  logo: "images/favicon.ico"
  favicon: "images/favicon.ico"

nav:
  - "Welcome": "index.md"
  - "REST API": 
    - "Info": "info.md"
    - "Products": "products.md"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
